name: Lint
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - run: sudo apt-get update && sudo apt-get install -y shellcheck yamllint
      - run: make lint
